CREATE TABLE contacts (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    subject VARCHAR(15),
    message TEXT NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


-- ---------------- 

CREATE TABLE feedbacks (
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY, 
    rating TINYINT NOT NULL , 
    email VARCHAR(15) NOT NULL , 
    feedback TEXT NULL ,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);